CREATE DATABASE DB_CUSTOMER
USE DB_CUSTOMER

CREATE TABLE TB_CUSTOMER(
ID_CUSTOMER INT PRIMARY KEY IDENTITY (1,1),
NM_CUSTOMER VARCHAR(50),
CPF_CNPJ BIGINT
)

CREATE TABLE SM_ADDRESS_TYPE(
CD_ADDRESS_TYPE CHAR(1) PRIMARY KEY,
DS_ADDRESS_TYPE VARCHAR(20)
)

CREATE TABLE TB_CUSTOMER_ADDRESS(
ID_CUSTOMER INT  REFERENCES TB_CUSTOMER(ID_CUSTOMER),
CD_ADDRESS_TYPE CHAR(1) REFERENCES SM_ADDRESS_TYPE(CD_ADDRESS_TYPE),
STREET VARCHAR(100),
LOT INT,
REFERENCE VARCHAR(100),
ZIP_COD VARCHAR (50),
CONSTRAINT PK_CUSTOMER_ADDRESS PRIMARY KEY(ID_CUSTOMER,CD_ADDRESS_TYPE)
)

INSERT INTO SM_ADDRESS_TYPE VALUES ('R','Residencial')
INSERT INTO SM_ADDRESS_TYPE VALUES ('C','Comercial')
INSERT INTO SM_ADDRESS_TYPE VALUES ('O','Outros')

INSERT INTO TB_CUSTOMER (NM_CUSTOMER,CPF_CNPJ) VALUES ('Joãozinho Silva', 88877766655)
INSERT INTO TB_CUSTOMER_ADDRESS VALUES ((SELECT TB_CUSTOMER.ID_CUSTOMER FROM TB_CUSTOMER WHERE CPF_CNPJ = 88877766655),'R','Rua das Flores',1,'','01234-567')
INSERT INTO TB_CUSTOMER_ADDRESS VALUES ((SELECT TB_CUSTOMER.ID_CUSTOMER FROM TB_CUSTOMER WHERE CPF_CNPJ = 88877766655),'C','Rua das Pedras',100,'Conjunto 200','01234-567')

SELECT * FROM TB_CUSTOMER
SELECT * FROM TB_CUSTOMER_ADDRESS

--Localizar o id do cliente 
--vou criar uma procedure para a exclusão de clientes 

CREATE PROCEDURE USP_EXCLUIR_CLIENTE 
@CPF_CNPJ BIGINT

AS BEGIN 
	DECLARE @ID_CUSTOMER INT =  (SELECT TB_CUSTOMER.ID_CUSTOMER FROM TB_CUSTOMER WHERE CPF_CNPJ = @CPF_CNPJ)
	DELETE FROM TB_CUSTOMER_ADDRESS WHERE ID_CUSTOMER = @ID_CUSTOMER
	DELETE FROM TB_CUSTOMER WHERE ID_CUSTOMER = @ID_CUSTOMER
END

EXEC USP_EXCLUIR_CLIENTE 88877766655